# Site settings
baseurl = "https://prmds.netlify.app/"
languageCode = "en-US"
title = "PRM with Data Science"
theme = "hugo-faq-theme"

# Do not build files for websites. Need them? Set to false
disableRSS = true
disableSitemap = true
disable404 = true

# Menu
SectionPagesMenu = "main"

	[[menu.main]]
		name = "Intro"
		weight = 10
		url = "#intro"
	[[menu.main]]
		name = "Entry Requirements"
		weight = 20
		url = "#entry"
  [[menu.main]]
		name = "Careers"
		weight = 30
		url = "#careers"
  [[menu.main]]
		name = "The Course"
		weight = 40
		url = "#course"
	[[menu.main]]
		name = "Colophon"
		weight = 60
		url = "#colophon"
[params]
	
	# Custom styling
	# To customize the styling of this theme, uncomment and edit the following line to point 
	# to your site's css in the assets/ directory. 

	custom_css = ["css/blue.css"]
	


